<x-app-layout>
<section class="card"><div class="card-header bg-danger text-white"><h5 class="mb-0">{{ $item->exists?'Edit':'Add' }} Neighbourhood</h5></div><div class="card-body">
<form method="POST" enctype="multipart/form-data" action="{{ $item->exists?route('neighbourhoods.update',$item):route('neighbourhoods.store') }}">@csrf @if($item->exists)@method('PUT')@endif
<div class="row">
<div class="col-md-6 mb-3"><label class="form-label">State</label><select id="state_id" name="state_id" class="form-select" required><option value="">Select State</option>@foreach($states as $state)<option value="{{ $state->id }}" @selected(old('state_id',$item->state_id)==$state->id)>{{ $state->name }}</option>@endforeach</select></div>
<div class="col-md-6 mb-3"><label class="form-label">City</label><select id="city_id" name="city_id" class="form-select" required><option value="">Select City</option>@foreach($cities as $city)<option value="{{ $city->id }}" data-state="{{ $city->state_id }}" @selected(old('city_id',$item->city_id)==$city->id)>{{ $city->name }}</option>@endforeach</select></div>
<div class="col-md-6 mb-3"><label class="form-label">Name</label><input name="name" class="form-control" value="{{ old('name',$item->name) }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Slug</label><input name="slug" class="form-control" value="{{ old('slug',$item->slug) }}" required></div>
<div class="col-12 mb-3"><label class="form-label">Summary</label><input name="summary" class="form-control" value="{{ old('summary',$item->summary) }}"></div>
@foreach(['banner_image'=>'Banner Image','main_image'=>'Main Gallery Image','side_image_one'=>'Side Gallery Image One','side_image_two'=>'Side Gallery Image Two'] as $field=>$label)
<div class="col-md-6 mb-4"><label for="{{ $field }}" class="form-label">{{ $label }}</label><input id="{{ $field }}" type="file" name="{{ $field }}" class="form-control image-upload" accept="image/jpeg,image/png,image/webp,image/gif" data-preview="{{ $field }}_preview"><small class="text-muted">JPG, PNG, WebP or GIF. Maximum 4 MB.</small><div id="{{ $field }}_preview_wrap" class="mt-2 {{ $item->$field ? '' : 'd-none' }}"><img id="{{ $field }}_preview" src="{{ $item->$field ? $item->imageUrl($field, '') : '' }}" alt="{{ $label }} preview" class="rounded border object-fit-cover" style="width:100%;max-width:320px;height:180px"><div><button type="button" class="btn btn-sm btn-danger mt-2 delete-image" data-field="{{ $field }}" data-existing="{{ $item->$field ? '1' : '0' }}">Delete Image</button></div></div></div>
@endforeach
<div class="col-md-4 mb-3"><label class="form-label">Days</label><input type="number" name="days" class="form-control" value="{{ old('days',$item->days?:4) }}" min="1" required></div><div class="col-md-4 mb-3"><label class="form-label">Nights</label><input type="number" name="nights" class="form-control" value="{{ old('nights',$item->nights??3) }}" min="0" required></div><div class="col-md-4 mb-3"><label class="form-label">Price</label><input type="number" step="0.01" name="price" class="form-control" value="{{ old('price',$item->price?:199) }}" min="0" required></div>
<div class="col-12 mb-3"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="4">{{ old('description',$item->description) }}</textarea></div><div class="col-12 mb-3"><label class="form-label">Overview</label><textarea name="overview" class="form-control" rows="4">{{ old('overview',$item->overview) }}</textarea></div>
<div class="col-12 mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label mb-0 fw-semibold">Tour Plan</label><button type="button" class="btn btn-sm btn-outline-primary add-row" data-target="tour-plan-rows" data-template="tour-plan-template"><i class="bi bi-plus-lg"></i> Add Day</button></div><div id="tour-plan-rows" class="repeater-rows">@foreach(old('tour_plan',$item->tour_plan??[]) as $index=>$day)<div class="repeater-row card bg-light border p-3 mb-2"><div class="row g-2"><div class="col-md-4"><input name="tour_plan[{{ $index }}][title]" class="form-control" value="{{ $day['title']??'' }}" placeholder="Day title"></div><div class="col-md-7"><textarea name="tour_plan[{{ $index }}][description]" class="form-control" rows="2" placeholder="Day description">{{ $day['description']??'' }}</textarea></div><div class="col-md-1 d-flex align-items-center justify-content-end"><button type="button" class="btn btn-sm btn-danger remove-row" aria-label="Remove day"><i class="bi bi-trash"></i></button></div></div></div>@endforeach</div></div>
@foreach(['highlights'=>'Highlights','inclusions'=>'Inclusions','exclusions'=>'Exclusions'] as $field=>$label)<div class="col-md-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label mb-0 fw-semibold">{{ $label }}</label><button type="button" class="btn btn-sm btn-outline-primary add-row" data-target="{{ $field }}-rows" data-template="list-row-template" data-field="{{ $field }}"><i class="bi bi-plus-lg"></i> Add</button></div><div id="{{ $field }}-rows" class="repeater-rows">@foreach(old($field,$item->$field??[]) as $value)<div class="repeater-row input-group mb-2"><input name="{{ $field }}[]" class="form-control" value="{{ $value }}" placeholder="Add {{ strtolower(rtrim($label,'s')) }}"><button type="button" class="btn btn-danger remove-row" aria-label="Remove row"><i class="bi bi-trash"></i></button></div>@endforeach</div></div>@endforeach
<div class="col-12 mb-3"><input type="hidden" name="status" value="0"><div class="form-check"><input id="status" type="checkbox" name="status" value="1" class="form-check-input" @checked((int)old('status',$item->exists?$item->status:1)===1)><label for="status" class="form-check-label">Active</label></div></div>
</div>@include('service-areas.validation-errors')<button class="btn btn-primary">Save Neighbourhood</button> <a href="{{ route('neighbourhoods.index') }}" class="btn btn-secondary">Cancel</a></form></div></section>
<template id="tour-plan-template"><div class="repeater-row card bg-light border p-3 mb-2"><div class="row g-2"><div class="col-md-4"><input data-name="tour_plan[__INDEX__][title]" class="form-control" placeholder="Day title"></div><div class="col-md-7"><textarea data-name="tour_plan[__INDEX__][description]" class="form-control" rows="2" placeholder="Day description"></textarea></div><div class="col-md-1 d-flex align-items-center justify-content-end"><button type="button" class="btn btn-sm btn-danger remove-row" aria-label="Remove day"><i class="bi bi-trash"></i></button></div></div></div></template>
<template id="list-row-template"><div class="repeater-row input-group mb-2"><input data-name="__FIELD__[]" class="form-control" placeholder="Add item"><button type="button" class="btn btn-danger remove-row" aria-label="Remove row"><i class="bi bi-trash"></i></button></div></template>
<script>
const state=document.getElementById('state_id'),city=document.getElementById('city_id'),options=[...city.options];
function filterCities(){options.forEach((option,index)=>{if(index)option.hidden=option.dataset.state!==state.value});if(city.selectedOptions[0]?.hidden)city.value=''}
state.addEventListener('change',filterCities);filterCities();
document.querySelectorAll('.image-upload').forEach(input=>input.addEventListener('change',()=>{const file=input.files[0],preview=document.getElementById(input.dataset.preview),wrap=document.getElementById(input.dataset.preview+'_wrap');if(file){preview.src=URL.createObjectURL(file);wrap.classList.remove('d-none');wrap.querySelector('.delete-image').dataset.existing='0'}}));
document.querySelectorAll('.delete-image').forEach(button=>button.addEventListener('click',async()=>{const field=button.dataset.field,input=document.getElementById(field),wrap=document.getElementById(field+'_preview_wrap');if(button.dataset.existing==='1'){
if(!confirm('Delete this image permanently?'))return;const url=@json($item->exists ? route('neighbourhoods.images.destroy', [$item, '__FIELD__']) : '');const response=await fetch(url.replace('__FIELD__',field),{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'}});if(!response.ok){alert('Unable to delete the image.');return;}}
input.value='';document.getElementById(field+'_preview').src='';wrap.classList.add('d-none');button.dataset.existing='0';}));
let tourPlanIndex={{ count(old('tour_plan',$item->tour_plan??[])) }};
document.querySelectorAll('.add-row').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.dataset.target),template=document.getElementById(button.dataset.template);let html=template.innerHTML;if(button.dataset.template==='tour-plan-template')html=html.replaceAll('__INDEX__',tourPlanIndex++);else html=html.replaceAll('__FIELD__',button.dataset.field);target.insertAdjacentHTML('beforeend',html);target.querySelectorAll('[data-name]').forEach(input=>{input.name=input.dataset.name;input.removeAttribute('data-name')});}));
document.addEventListener('click',event=>{const button=event.target.closest('.remove-row');if(button)button.closest('.repeater-row').remove()});
</script>
</x-app-layout>
